title: Courtney Vincent
logo: /Courtney%20Vincent%20Headshot.jpg
description: >
  Master’s student in Business Analytics at Boston University. 
  Passionate about data-driven strategy, modeling, and storytelling.

theme: jekyll-theme-minimal

